### ISSUE TITLE
Avoid using Keyboard/Screen during first boot

### ISSUE THREAD

**Issue by dzervas** [smeathers/lede-pi0w-usb#2]
In order to avoid the need of keyboard/screen, you can edit `/etc/config/wireless` and make `disable='0'` under `radio0`. The "data" partition is the second one.

**Comment by smeathers** [comment]
> 
> 
> In order to avoid the need of keyboard/screen, you can edit `/etc/config/wireless` and make `disable='0'` under `radio0`. The "data" partition is the second one.

Interesting.  Looking into that this evening.  I've formatted a new SD card with openwrt-18.06.1-brcm2708-bcm2708-rpi-ext4-factory.img and mounting the partition I can't see an existing wireless file in /etc/config/  do I have to boot it once for the file to be created?

**Comment by smeathers** [comment]
Thanks @dzervas I've just managed to get that working.  I've been trying to get it all working with a later build of OpenWRT and this will greatly speed productivity.  Cheers.

**Comment by yuanlixg** [comment]
/etc/config/wireless not exist before first boot.
must power on once.
sorry, my english is poor.

BTW:
(1) join_wifi.png maybe select(dot): LAN
(2)
opkg update
opkg install kmod-usb-gadget-eth
opkg install kmod-usb-dwc2
echo 'dtoverlay=dwc2' >> /boot/config.txt
halt
